gTexto_Bienvenida_Malak::
gText_Birch_Welcome::
	.string "¡Qué onda! Perdón por la demora,\n"
	.string "pero ya estamos aquí.\p"
	.string "Soy MALAK, y te doy la bienvenida\n"
	.string "oficial al mundo de LEYENDA REGIONAL.\p"
	.string "Muchos ya me conocen por los videos\n"
	.string "en TikTok y YouTube como Malak Legends.\p"
	.string "Como Creador y ROM Hacker, le he\n"
	.string "echado todas las ganas a este proyecto.\p"
	.string "Lo que empezó en Pokémon Cristal\n"
	.string "Retodex, hoy es de otro nivel.\p"
	.string "Conectaremos regiones que antes\n"
	.string "estaban separadas por puro código.\p"
	.string "Prepárate para viajar lejos y\n"
	.string "descubrir secretos bien ocultos.\p"
	.string "En Malak Legends, cada ruta y cada\n"
	.string "POKéMON son parte de una gran historia.\p"
	.string "Estamos construyendo este universo\n"
	.string "paso a paso, como comunidad.\p"
	.string "Dime... ¿Tienes el valor suficiente\n"
	.string "para entrarle a este nuevo horizonte?\p"
	.string "¡Órale, es hora de que comience\n"
	.string "tu propia LEYENDA REGIONAL!\p"
	.string "$"

gTexto_Malak_Pokemon::
gText_Birch_Pokemon::
	.string "Como ves, este mundo está habitado.\p"
	.string "\n"
	.string "$"

gTexto_Central::
gText_Birch_MainSpeech::
	.string "Estas criaturas son increíbles.\p"
	.string "Como ROM Hacker, he visto cómo sus\n"
	.string "datos cobran vida para darnos las\l"
	.string "batallas más épicas de la región.\p"
	.string "Unos juegan con ellos, otros los usan\n"
	.string "para trabajar... pero nosotros no.\p"
	.string "Nosotros vamos a demostrar por qué\n"
	.string "esta comunidad es la más fuerte.\p"
	.string "Trátalos con respeto y entrena duro,\n"
	.string "porque aquí nadie te va a regalar nada.\p"
	.string "¡Demuéstrame de qué estás hecho y\n"
	.string "conviértete en una leyenda de verdad!$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gTexto_Cambiar_Nombre::
gText_Birch_WhatsYourName::
	.string "Y ahora lo más importante...\p"
	.string "¿Quieres llevar mi nombre como tributo\n"
	.string "o prefieres escribir tu propia historia?$"

gTexto_Confirmar_Nombrer::
gText_Birch_SoItsPlayer::
	.string "¿Estás seguro que quieres llamarte\n"
	.string "{PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "¡Ah, ya veo!\p"
	.string "Eres {PLAYER}{KUN}, y tu historia\n"
	.string "apenas está por comenzar.\p"
	.string "$"

gTexto_Malak_listo::
gText_Birch_AreYouReady::
	.string "¡Perfecto! Ya está todo listo.\p"
	.string "Las regiones te esperan y el destino\n"
	.string "de Malak Legends está en tus manos.\p"
	.string "¿Estás listo para esta gran aventura?$"
